version: '3.8'
services:
  api:
    container_name: quake-log-parser
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    hostname: balder
    ports:
      - "3000:3000"
    restart: on-failure